# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 764)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 764))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#MainWindow {\n"
"    background: #000;\n"
"}\n"
"\n"
"#mainView, #plateView, #plateDecodedLabel {\n"
"    border: 3px solid #00e19d;\n"
"    border-radius: 20px;\n"
"    background: rgba(255, 252, 252, 0.15);\n"
"}\n"
"\n"
"#menubar {\n"
"    background: #000;\n"
"    color: #fff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #000;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setMinimumSize(QtCore.QSize(960, 520))
        self.mainFrame.setSizeIncrement(QtCore.QSize(16, 9))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainFrame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.mainView = QtWidgets.QLabel(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainView.sizePolicy().hasHeightForWidth())
        self.mainView.setSizePolicy(sizePolicy)
        self.mainView.setSizeIncrement(QtCore.QSize(16, 9))
        self.mainView.setText("")
        self.mainView.setAlignment(QtCore.Qt.AlignCenter)
        self.mainView.setObjectName("mainView")
        self.gridLayout_3.addWidget(self.mainView, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mainFrame, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(960, 122))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plateDecodedFrame = QtWidgets.QFrame(self.frame_5)
        self.plateDecodedFrame.setMinimumSize(QtCore.QSize(260, 56))
        self.plateDecodedFrame.setSizeIncrement(QtCore.QSize(16, 9))
        self.plateDecodedFrame.setStyleSheet("#plateDecodedLabel {\n"
"    color: #fff;\n"
"}")
        self.plateDecodedFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plateDecodedFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plateDecodedFrame.setObjectName("plateDecodedFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.plateDecodedFrame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plateDecodedLabel = QtWidgets.QLabel(self.plateDecodedFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.plateDecodedLabel.setFont(font)
        self.plateDecodedLabel.setLineWidth(6)
        self.plateDecodedLabel.setText("")
        self.plateDecodedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.plateDecodedLabel.setObjectName("plateDecodedLabel")
        self.gridLayout_5.addWidget(self.plateDecodedLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.plateDecodedFrame, 1, 0, 1, 1)
        self.plateFrame = QtWidgets.QFrame(self.frame_5)
        self.plateFrame.setMinimumSize(QtCore.QSize(260, 56))
        self.plateFrame.setSizeIncrement(QtCore.QSize(16, 9))
        self.plateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plateFrame.setObjectName("plateFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.plateFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plateView = QtWidgets.QLabel(self.plateFrame)
        self.plateView.setText("")
        self.plateView.setAlignment(QtCore.Qt.AlignCenter)
        self.plateView.setObjectName("plateView")
        self.gridLayout_4.addWidget(self.plateView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.plateFrame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMinimumSize(QtCore.QSize(690, 0))
        self.frame_4.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setSpacing(15)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelDetAcc = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.labelDetAcc.setFont(font)
        self.labelDetAcc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDetAcc.setObjectName("labelDetAcc")
        self.gridLayout_6.addWidget(self.labelDetAcc, 1, 1, 1, 1)
        self.labelClsModel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.labelClsModel.setFont(font)
        self.labelClsModel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClsModel.setObjectName("labelClsModel")
        self.gridLayout_6.addWidget(self.labelClsModel, 0, 0, 1, 1)
        self.labelDetModel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.labelDetModel.setFont(font)
        self.labelDetModel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDetModel.setObjectName("labelDetModel")
        self.gridLayout_6.addWidget(self.labelDetModel, 0, 1, 1, 1)
        self.labelTime = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.labelTime.setFont(font)
        self.labelTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout_6.addWidget(self.labelTime, 1, 0, 1, 1)
        self.labelClsAcc = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.labelClsAcc.setFont(font)
        self.labelClsAcc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClsAcc.setObjectName("labelClsAcc")
        self.gridLayout_6.addWidget(self.labelClsAcc, 0, 2, 2, 1)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 2, 1)
        self.gridLayout_2.addWidget(self.frame_5, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setStyleSheet("QPushButton {\n"
"    border-bottom: 1px solid #00e19d;\n"
"    border-top: 2px solid #00e19d;\n"
"    border-radius: 10px;\n"
"    background: #000;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00e19d; \n"
"}\n"
"\n"
"QPushButtom:focus {\n"
"    background-color: #00E1B8;\n"
"    border: 10px solid #00E1B8;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.debugBtn = QtWidgets.QPushButton(self.frame_6)
        self.debugBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.debugBtn.setFont(font)
        self.debugBtn.setObjectName("debugBtn")
        self.horizontalLayout.addWidget(self.debugBtn)
        self.detectBtn = QtWidgets.QPushButton(self.frame_6)
        self.detectBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.detectBtn.setFont(font)
        self.detectBtn.setObjectName("detectBtn")
        self.horizontalLayout.addWidget(self.detectBtn)
        self.gridLayout_2.addWidget(self.frame_6, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 19))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.menuSettings.addAction(self.actionOpen)
        self.menuSettings.addAction(self.actionSettings)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Обнаружение"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.labelDetAcc.setText(_translate("MainWindow", "Точность обнаружения: 80%"))
        self.labelClsModel.setText(_translate("MainWindow", "Модель классификации: YOLO8n-200e"))
        self.labelDetModel.setText(_translate("MainWindow", "Модель обнаружения: YOLO8s-100e"))
        self.labelTime.setText(_translate("MainWindow", "Затраченное время: 10ms"))
        self.labelClsAcc.setText(_translate("MainWindow", "Точность классификации:\n"
"O - 70%\n"
"7 - 66%\n"
"6 - 52%\n"
"9 - 97%\n"
"D - 84%\n"
"T - 90%"))
        self.debugBtn.setText(_translate("MainWindow", "Отладка"))
        self.detectBtn.setText(_translate("MainWindow", "Обнаружение"))
        self.menuSettings.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
