# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelClsModel = QtWidgets.QLabel(Dialog)
        self.labelClsModel.setObjectName("labelClsModel")
        self.gridLayout.addWidget(self.labelClsModel, 0, 1, 1, 1)
        self.selectClsModel = QtWidgets.QPushButton(Dialog)
        self.selectClsModel.setObjectName("selectClsModel")
        self.gridLayout.addWidget(self.selectClsModel, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.labelDetModel = QtWidgets.QLabel(Dialog)
        self.labelDetModel.setObjectName("labelDetModel")
        self.gridLayout.addWidget(self.labelDetModel, 1, 1, 1, 1)
        self.selectDetModel = QtWidgets.QPushButton(Dialog)
        self.selectDetModel.setObjectName("selectDetModel")
        self.gridLayout.addWidget(self.selectDetModel, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.threshBox = QtWidgets.QSpinBox(Dialog)
        self.threshBox.setMaximum(255)
        self.threshBox.setProperty("value", 150)
        self.threshBox.setObjectName("threshBox")
        self.gridLayout.addWidget(self.threshBox, 2, 1, 1, 1)
        self.saveBtn = QtWidgets.QPushButton(Dialog)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout.addWidget(self.saveBtn, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Classification model: "))
        self.labelClsModel.setText(_translate("Dialog", "TextLabel"))
        self.selectClsModel.setText(_translate("Dialog", "Edit"))
        self.label.setText(_translate("Dialog", "Detection model:"))
        self.labelDetModel.setText(_translate("Dialog", "TextLabel"))
        self.selectDetModel.setText(_translate("Dialog", "Edit"))
        self.label_5.setText(_translate("Dialog", "Threshold"))
        self.saveBtn.setText(_translate("Dialog", "Save"))
